spring:
  main:
    allow-circular-references: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test_id
            client-secret: test_secret
            scope:
              - email
              - profile
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
  h2:
    console:
      enabled: true
jwt:
  issuer: ajufresh@gmail.com
  secret_key: test_key